# Form implementation generated from reading ui file 'D:\HOANG VY\LAPTRINH\HK2\FINAL_PROJECT\Mainwindowuser.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(445, 331)
        MainWindow.setStyleSheet("background-color:rgb(250, 232, 237)")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonEXIT = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonEXIT.setGeometry(QtCore.QRect(375, 9, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEXIT.setFont(font)
        self.pushButtonEXIT.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(199, 125, 231);\n"
"\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/HOANG VY/Users/HOANG VY/Downloads/1564506_close_exit_logout_power_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonEXIT.setIcon(icon)
        self.pushButtonEXIT.setObjectName("pushButtonEXIT")
        self.pushButtonREAD = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonREAD.setGeometry(QtCore.QRect(90, 240, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonREAD.setFont(font)
        self.pushButtonREAD.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(199, 125, 231);\n"
"\n"
"\n"
"\n"
"")
        self.pushButtonREAD.setObjectName("pushButtonREAD")
        self.pushButtonWRITRE = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonWRITRE.setGeometry(QtCore.QRect(230, 240, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonWRITRE.setFont(font)
        self.pushButtonWRITRE.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(199, 125, 231);\n"
"\n"
"\n"
"\n"
"")
        self.pushButtonWRITRE.setObjectName("pushButtonWRITRE")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 231, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/HOANG VY/Downloads/Harper Russo (1).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 445, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButtonEXIT.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonEXIT.setText(_translate("MainWindow", "Exit"))
        self.pushButtonREAD.setText(_translate("MainWindow", "READ "))
        self.pushButtonWRITRE.setText(_translate("MainWindow", "WRITE"))
